# Date/time
MICROSECONDS_PER_SEC = 1_000_000
MICROSECONDS_STR = "us"
MICROSECONDS_STR_INFLUX = "u"

# Catalog
CATALOG_NAME: str = "isis"
SOURCE_NAMESPACE_PREFIX: str = "sources_"
SOURCE_TABLE_PREFIX: str = "raw_"
