#!/bin/sh
# Jupyter Notebook server
#
NOTEBOOKS_DIR=${NOTEBOOKS_DIR:-/var/lib/jupyter/notebooks}

jupyter-notebook \
  --notebook-dir=${NOTEBOOKS_DIR} \
  --ip="*" \
  --NotebookApp.token="" \
  --NotebookApp.password="" \
  --port=8888 \
  --no-browser \
  --allow-root
