# syntax=docker/dockerfile
# WARNING: This needs to match the version running in JupyterHub
FROM python:3.12-bookworm

# Arguments
ARG SPARK_DOWNLOAD_BASE_URL=https://archive.apache.org/dist/spark
ARG SPARK_VERSION=3.5.2

# Environment
ENV SPARK_HOME=/opt/spark

# Basic configuration
ENV PATH="${SPARK_HOME}/sbin:${SPARK_HOME}/bin:${PATH}"
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  sudo \
  curl \
  unzip \
  openjdk-17-jdk \
  build-essential \
  software-properties-common && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Dirs
RUN mkdir -p \
  ${SPARK_HOME} \
  ${SPARK_HOME}/logs \
  ${SPARK_HOME}/spark-events
WORKDIR ${SPARK_HOME}

# Spark
RUN curl ${SPARK_DOWNLOAD_BASE_URL}/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz -o spark-${SPARK_VERSION}-bin-hadoop3.tgz \
  && tar xvzf spark-${SPARK_VERSION}-bin-hadoop3.tgz --directory ${SPARK_HOME} --strip-components 1 \
  && rm -rf spark-${SPARK_VERSION}-bin-hadoop3.tgz

# File modes
RUN chmod u+x ${SPARK_HOME}/sbin/* && \
  chmod u+x ${SPARK_HOME}/bin/*
